### ISSUE TITLE
build fails, missing package/xbmc/tvheadend directory

### ISSUE THREAD

**Issue by dashxdr** [huceke/buildroot-rbp#1]
commit 001ccb71cc0f01ef8c4529512312a7c697d09275

Build fails with this:
$ make rbp_defconfig
package/xbmc/Config.in:23: can't open file "package/xbmc/tvheadend/Config.in"
make: **\* [rbp_defconfig] Error 1

The referenced directory is not included in the git repository.

**Comment by huceke** [comment]
Added the missing package.
